[project]
name = "opinion-galaxy-mvp"
version = "0.1.0"
description = ""
authors = [{ name = "edegp", email = "a.yuhi1164@gmail.com" }]
readme = "README.md"
requires-python = "3.12.8"
dependencies = [
    "streamlit (==1.41.1)",
    "pandas (==2.2.3)",
    "pygwalker (==0.4.9.9)",
    "numpy (==1.26.4)",
    "plotly (==5.24.1)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
